Models/RebateRedemption.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LixilRebate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RebateRedemption
    {
        public int id { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<int> State { get; set; }
        public string Zip { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> RebateId { get; set; }
        public string ReceiveRebateOption { get; set; }
        public Nullable<int> BuilderId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsAuthorized { get; set; }
    }
}

ViewModels/RebateRedemptionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using LixilRebate.Attributes;

namespace LixilRebate.ViewModels
{
    public class RebateRedemptionViewModel
    {
        public int id { get; set; }

        [Display(Name = "Name funds should be sent to ")]
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }

        [Display(Name = "Address")]
        [Required(ErrorMessage = "Address is required")]
        public string Address1 { get; set; }

        [Display(Name = "Address 2")]
        public string Address2 { get; set; }

        [Required(ErrorMessage = "City is required")]
        public string City { get; set; }

        [Required(ErrorMessage = "State is required")]
        public int? State { get; set; }
        public string StateName { get; set; }

        [Required(ErrorMessage = "Zip is required")]
        [RegularExpression(@"^(\d{5})$", ErrorMessage = "Zip is not valid.")]
        public string Zip { get; set; }

        [EnforceTrue(ErrorMessage = "This field is required")]

        //[CustomValidation(typeof(BoolValidation), "ValidateBool")]
        public bool IsAutorized { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }
        public bool? IsActive { get; set; }
        public int? RebateId { get; set; }

        [Display(Name = "Receive Rebate Option")]
        [Required(ErrorMessage = "Receive Rebate Option is required")]
        public string ReceiveRebateOption { get; set; }
        public int? BuilderId { get; set; }        

        
    }
}

Controllers/BuilderController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.HtmlControls;
using AutoMapper;
using LixilRebate.App_Start;
using LixilRebate.Models;
using LixilRebate.ViewModels;
using LixilRebate.Constants;
using System.Collections;
using System.Text;
using System.Security.Cryptography;

namespace LixilRebate.Controllers
{
    public class BuilderController : Controller
    {
        private readonly DBContext _db = new DBContext();
        int _builderId = 0;
        // GET: Builder
        public ActionResult Index()
        {
            if (Request.Cookies["UserId"] != null)
            {
                _builderId = Convert.ToInt32(Request.Cookies["UserId"].Value);
                StatusProgressViewModel progressDetails = GetBuilder(_builderId);
                return View(progressDetails);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public StatusProgressViewModel GetBuilder(int builderId)
        {
            //var config = new AutoMapperConfig().Configure();
            //IMapper iMapper = config.CreateMapper();

            var user = new User();
            user = _db.Users.Where(a => a.Id == builderId && a.RoleId == 5).FirstOrDefault();
            var contractDetails = new ContractDetail();

            if (_db.ContractDetails.Any(x => x.BuilderId == builderId))
            {
                contractDetails = _db.ContractDetails.Where(x => x.BuilderId == builderId).First();
            }
            var builder = new StatusProgressViewModel()
            {
                BuilderStatusId = (int)user.BuilderStatusId,
                RegistrationSubmitted = (DateTime)user.CreatedDate,
                RegistrationModified = user.ModifiedDate,
                ContractSubmitted = contractDetails.CreatedDate,
                ContractModified = contractDetails.ModifiedDate,
                ContractModifiedBy = contractDetails.ModifiedBy,
                RegistrationModifiedBy = user.ModifiedBy,
                Type = user.Type,
                IsContractDateExpired = false
            };
            if (contractDetails.ExpirationDate != null)
            {
                if (Convert.ToDateTime(DateTime.Now.ToString("MM/dd/yyyy")) > Convert.ToDateTime(contractDetails.ExpirationDate.Value.ToString("MM/dd/yyyy")))
                {
                    builder.IsContractDateExpired = true;
                }
            }
            if (contractDetails.ContractStatus != null)
            {
                builder.ContractStatusId = contractDetails.ContractStatus;
            }
            else
            {
                builder.ContractStatusId = 1;
            }
            return builder;
        }

        [HttpGet]
        public ActionResult RebateForRewards(string invoiceDate = null, string invoiceNumber = null, bool secondRequest = false)
        {
            var products = _db.Products.ToList();



            List<ProductViewModel> productViews = new List<ProductViewModel>();

            foreach (var product in products)
            {
                ProductViewModel productViewModel = new ProductViewModel();
                productViewModel.SKU = product.SKU;
                string mfgName = _db.Manufacturers.Where(x => x.id == product.Manufacturer).Select(a => a.mfg_name).FirstOrDefault();
                productViewModel.SKU = product.SKU + " - " + mfgName;
                productViewModel.Id = product.Id;
                productViews.Add(productViewModel);
            }

            ViewBag.Products = new SelectList(productViews, "Id", "SKU");

            //var manufacturers = _db.Manufacturers.ToList();
            //ViewBag.Manufacturers = new SelectList(manufacturers,"id","mfg_name");

            RebateRewardsViewModel rewardsViewModel = new RebateRewardsViewModel();

            if (invoiceDate != null && invoiceNumber != null)
            {
                rewardsViewModel.DistributorInvoiceDate = invoiceDate;
                rewardsViewModel.DistributorInvoiceNumber = invoiceNumber;
               // rewardsViewModel.secondRequest = secondRequest;
                
            }

            rewardsViewModel.secondRequest = secondRequest;
            return View(rewardsViewModel);
        }

        //[HttpPost]
        //public JsonResult GetProducts(int prefix)
        //{
        //    var products = _db.Products.ToList();
        //    var similarProducts = (from product in products
        //                           where product.ProductNumber.StartsWith(prefix.ToString())
        //                           select new { product.ProductNumber });
        //    return Json(similarProducts, JsonRequestBehavior.AllowGet);
        //}

        [HttpPost]
        public ActionResult RebateForRewards(RebateRewardsViewModel rebateRewards)
        {
            try
            {
                var user = new User();
                _builderId = Convert.ToInt32(Request.Cookies["UserId"].Value);
                user = _db.Users.Where(a => a.Id == _builderId && a.RoleId == 5).FirstOrDefault();


                if (user != null)
                {
                    RebateDetail rebateDetails = new RebateDetail();
                    var RNumber = "";
                    //if (rebateRewards.secondRequest == true)
                    //{
                    //    rebateRewards.RebateId = _db.RebateDetails.Max(x => x.Id);
                    //}
                    if (rebateRewards.secondRequest == false)
                    {
                        RNumber = GetUniqueKey(12);
                        //bool isRebateExist = _db.RebateDetails.Any(x => x.BuilderId == user.Id && x.Type == user.Type);


                        //if (isRebateExist)
                        //{
                        //    rebateDetails.Id = _db.RebateDetails.Where(x => x.BuilderId == user.Id && x.Type == user.Type).Select(x => x.Id).First();
                        //}
                        //else
                        //{
                        rebateDetails.BuilderId = user.Id;
                        rebateDetails.Type = (int)user.Type;
                        rebateDetails.CreatedDate = DateTime.Now;
                        rebateDetails.ModifiedDate = DateTime.Now;
                        rebateDetails.IsActive = true;
                        _db.RebateDetails.Add(rebateDetails);
                        _db.SaveChanges();
                        //}

                        RebateReward rebateReward = new RebateReward()
                        {
                            BuilderId = user.Id,
                            RebateId = rebateDetails.Id,
                            DistributorInvoiceDate = rebateRewards.DistributorInvoiceDate,
                            DistributorInvoiceNumber = rebateRewards.DistributorInvoiceNumber,
                            RecordNumber = RNumber,
                            Status = 2,
                            CreatedDate = DateTime.Now,
                            ModifiedDate = DateTime.Now,
                            IsActive = false
                        };

                        _db.RebateRewards.Add(rebateReward);
                        _db.SaveChanges();

                        _db.Entry(rebateReward).State = System.Data.Entity.EntityState.Detached;
                    }

                    rebateRewards.RebateId = _db.RebateDetails.Max(x => x.Id);

                    //string text = rebateRewards.ProductNumber;
                    //string[] parts = text.Split('-');
                    //string productNumber = parts[0];
                    //string Mfg = parts[1];

                    int productId = Convert.ToInt32(rebateRewards.ProductNumber);
                    var product = _db.Products.Where(x => x.Id == productId).First();

                    //int mfg_name = Convert.ToInt32(rebateRewards.MfgName);
                    InvoiceProduct invoiceProduct = new InvoiceProduct()
                    {
                        InvoiceNumber = rebateRewards.DistributorInvoiceNumber,
                        BuilderId = _builderId,
                        ProductNumber = product.SKU,
                        Quantity = rebateRewards.Quantity,
                        Manufacturer = product.Manufacturer,
                        CreatedDate = DateTime.Now,
                        ModifiedDate = DateTime.Now,
                        IsActive = true
                    };


                    //var product = _db.Products.Where(x => x.SKU == rebateRewards.ProductNumber && x.Manufacturer == mfg_name).First();
                    var manfacturer = product.Manufacturer;
                    var price = product.ListPrice;
                    var percentage = _db.Manufacturers.Where(x => x.id == manfacturer).Select(a => a.Percentage).First();
                    var quantity = rebateRewards.Quantity;



                    invoiceProduct.DollarEstimated = ((price * quantity) * (percentage / 100)).ToString();
                    //invoiceProduct.DollarEstimated = "$" + invoiceProduct.DollarEstimated;

                    _db.InvoiceProducts.Add(invoiceProduct);
                    _db.SaveChanges();

                    var dollarEstimated = 0.0;
                    var products = _db.InvoiceProducts.Where(x => x.InvoiceNumber == rebateRewards.DistributorInvoiceNumber && x.BuilderId == _builderId).ToList();

                    if (products.Count > 0)
                    {
                        foreach (var product1 in products)
                        {
                            dollarEstimated = dollarEstimated + Convert.ToDouble(product1.DollarEstimated);
                        }
                        rebateRewards.DollarEstimated = dollarEstimated.ToString();

                        RebateReward reward = new RebateReward();

Views/Builder/RebateForSelect.cshtml
@model LixilRebate.ViewModels.RebateSelectViewModel


<!DOCTYPE html>
<html lang="en">


<body class="layout-fixed sidebar-collapse">
    <div class="wrapper ">


        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <!-- Main content -->
            <section class="content">
                <div class="container">


                    <div class="row">

                        <div class="col-md-12 ">
                            <h3 class="form_headline mt-2 mb-3">Enter Rebate for Select</h3>


                            <div class="card">

                                <div class="card-body">
                                    @using (Html.BeginForm("RebateForSelect", "Builder", FormMethod.Post, new { enctype = "multipart/form-data", autocomplete = "off" }))
                                    {
                                        @Html.AntiForgeryToken()
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                        <div class="row">

                                            <div class="col-md-3 mb-2">
                                                <div class="form-group">
                                                    <label><sup>*</sup>Subdivision Name </label>
                                                    @Html.EditorFor(model => model.SubDivisionName, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.SubDivisionName, "", new { @class = "text-danger" })
                                                </div>
                                                <!-- <div class="error_msg">Required</div> -->
                                            </div>


                                            <div class="col-md-3 mb-2">
                                                <div class="form-group">
                                                    <label>
                                                        <sup>*</sup>Lot #:
                                                    </label>
                                                    @Html.EditorFor(model => model.Lot_, new { htmlAttributes = new { @class = "form-control", @type = "number",@min = "1" } })
                                                    @Html.ValidationMessageFor(model => model.Lot_, "", new { @class = "text-danger" })
                                                </div>
                                                <!-- <div class="error_msg">Required</div> -->
                                            </div>



                                            <div class="col-md-3 mb-2">
                                                <div class="form-group">
                                                    <label>
                                                        <sup>*</sup>Per Home Rebate:
                                                    </label>
                                                    <div class="input-group mb-3">
                                                        <div class="input-group-prepend">
                                                            <span class="input-group-text">$</span>
                                                        </div>
                                                        @Html.EditorFor(model => model.PerHomeRebate, new { htmlAttributes = new { @class = "form-control", @type = "number",@min = "1"} })

                                                    </div>
                                                    @Html.ValidationMessageFor(model => model.PerHomeRebate, "", new { @class = "text-danger" })
                                                </div>
                                                <!-- <div class="error_msg">Required</div> -->
                                            </div>

                                            <div class="col-md-3 mb-2">
                                                <div class="form-group">
                                                    <label for="inputName">
                                                        <sup>*</sup>Closing Statement Date:
                                                    </label>
                                                    <div class="input-group date" id="reservationdate" data-target-input="nearest">
                                                        @Html.EditorFor(model => model.ClosingStatementDate, new { htmlAttributes = new { @class = "form-control", @id = "closingDate" } })

                                                        <div class="input-group-append" data-target="#reservationdate"
                                                             data-toggle="datetimepicker">
                                                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                                        </div>
                                                    </div>
                                                    @Html.ValidationMessageFor(model => model.ClosingStatementDate, "", new { @class = "text-danger" })
                                                </div>
                                                <!-- <div class="error_msg">Required</div> -->
                                            </div>

                                        </div>




                                        <div class="row mt-3">
                                            <div class="col-md-12">
                                                <div class="col-md-6 mb-3">
                                                    <div class="form-group">
                                                        <label for="exampleInputFile"><sup>*</sup>Upload Closing Statement </label>
                                                        <div class="input-group">
                                                            <div class="custom-file">
                                                                @Html.TextBoxFor(model => model.InvoiceFile, "", new { @class = "custom-file-input", @type = "file", @multiple = "multiple" })
                                                                <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                                            </div>

                                                        </div>
                                                        @Html.ValidationMessageFor(model => model.InvoiceFile, "", new { @class = "text-danger" })
                                                    </div>
                                                    <!-- <div class="error_msg">Required</div> -->
                                                </div>

                                            </div>


                                        </div>

                                        <div class="row mt-3">
                                            <div class="col-md-6">
                                                <button type="submit" class="btn btn-secondary">Submit</button>
                                            </div>
                                        </div>



                                    }
                                </div>
                                <div style="clear: both;"></div>
                            </div>

                        </div>

                    </div>

                    <!-- /.row -->


                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->



    </div>
    <!-- ./wrapper -->

</body>

</html>

@*<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

<script src="~/plugins/select2/js/select2.full.min.js"></script>*@





<script>

    $(document).ready(function () {

        $('#reservationdate').datetimepicker({
            format: 'L',
            maxDate:'now',
            endDate:'+0d',
            ignoreReadonly: true,
            autoclose: true,
        });
    });

    $(".custom-file-input").on("change", function () {
        var files = $(this)[0].files.length;
        if (files > 0)
            $('.custom-file-label').html("" + files + " file(s) selected");
        else
            $('.custom-file-label').html("Choose files");
    });

</script>

Views/Builder/RebateStatusForRewards.cshtml
@model IEnumerable<LixilRebate.ViewModels.RebateRewardsViewModel>

<body class="layout-fixed sidebar-collapse">
    <div class="wrapper ">

        <!-- Navbar -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <!-- Main content -->
            <section class="content">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 ">
                            <h3 class="form_headline mt-2 mb-3">View Rebate Status</h3>
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">

                                        <div class="col-md-12 mb-2">
                                            <table class="table table-bordered">
                                                <tr>
                                                    <th>Order Number</th>
                                                    <th>Invoice Number</th>
                                                    <th>Invoice Submitted</th>
                                                    <th>Dollar Estimated</th>
                                                    <th>Status</th>
                                                    <th>Approved/Denied Date</th>
                                                    <th>Dollar Approved</th>
                                                </tr>

                                                @foreach (var invoice in Model)
                                                {
                                            <tr>
                                                <td><a href="@Url.Action("InvoiceInformation","Builder",new { orderNumber = invoice.OrderNumber})">@invoice.OrderNumber</a></td>
                                                <td>@invoice.DistributorInvoiceNumber</td>
                                                <td>@invoice.CreatedDate.Value.ToString("MM/dd/yyyy")</td>
                                                <td>@invoice.DollarEstimated</td>
                                                <td>@invoice.Status</td>
                                                @if (invoice.ApprovedOrDeniedDate != null)
                                                {
                                                    <td>@invoice.ApprovedOrDeniedDate.Value.ToString("MM/dd/yyyy")</td>
                                                }
                                                else
                                                {
                                                    <td>-</td>
                                                }
                                                @*<td>@invoice.StatusDate</td>*@
                                                <td>@invoice.DollarApproved</td>
                                            </tr>
                                                }


                                            </table>
                                        </div>
                                    </div>
                                    @*<div class="row mt-5">
                                            <div class="col-md-12 mb-2">
                                                <div class="form-group row">
                                                    <label for="inputEmail3" class="col-sm-3 col-form-label">
                                                        Invoices
                                                        Approved/Denied:
                                                    </label>
                                                    <div class="col-sm-9 pt-2">
                                                        @ViewBag.Status
                                                    </div>
                                                </div>
                                            </div>
                                        </div>*@
                                </div>
                                <div style="clear: both;"></div>
                            </div>
                        </div>
                    </div>

                    <!-- /.row -->


                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->



    </div>
    <!-- ./wrapper -->



</body>

Views/Builder/RebateStatusForSelect.cshtml
@model IEnumerable<LixilRebate.ViewModels.RebateSelectViewModel>

@*@{
        ViewBag.Title = "RebateStatusForSelect";
    }*@

<body class="layout-fixed sidebar-collapse">
    <div class="wrapper ">

        <!-- Navbar -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <!-- Main content -->
            <section class="content">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 ">
                            <h3 class="form_headline mt-2 mb-3">View Rebate Status</h3>
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">

                                        <div class="col-md-12 mb-2">
                                            <table class="table table-bordered">
                                                <tr>
                                                    <th>Order Number</th>
                                                    <th>Rebate Submitted</th>
                                                    <th>Status</th>
                                                    <th>Approved/Denied Date</th>
                                                    <th>Dollar Estimated</th>
                                                    <th>Dollar Approved</th>
                                                </tr>
                                                @foreach (var rebate in Model)
                                                {
                                            <tr>
                                                <td>
                                                    <a href="@Url.Action("SelectInvoiceInformation","Builder",new { orderNumber = rebate.OrderNumber})">@rebate.OrderNumber</a>
                                                </td>
                                                <td>@rebate.CreatedDate.Value.ToString("MM/dd/yyyy")</td>
                                                <td>@rebate.Status</td>
                                                @if (rebate.ApprovedorDeniedDate != null)
                                                {
                                                    <td>@rebate.ApprovedorDeniedDate.Value.ToString("MM/dd/yyyy")</td>
                                                }
                                                else
                                                {
                                                    <td>-</td>
                                                }
                                                @if(rebate.DollarEstimated != null)
                                                {
                                                    <td>$@rebate.DollarEstimated</td>
                                                }
                                                else
                                                {
                                                    <td>-</td>
                                                }
                                                <td>@rebate.ApprovedAmount</td>
                                            </tr>
                                                }

                                            </table>
                                        </div>
                                    </div>
                                    @*<div class="row mt-5">
                                            <div class="col-md-12 mb-2">
                                                <div class="form-group row">
                                                    <label for="inputEmail3" class="col-sm-3 col-form-label">
                                                        Invoices
                                                        Approved/Denied:
                                                    </label>
                                                    <div class="col-sm-9 pt-2">
                                                        @ViewBag.Status
                                                    </div>
                                                </div>
                                            </div>
                                        </div>*@
                                </div>
                                <div style="clear: both;"></div>
                            </div>
                        </div>
                    </div>

                    <!-- /.row -->


                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->



    </div>
    <!-- ./wrapper -->



</body>